---
title: "Study material"
author: "`r authors`"
date: "`r Sys.Date()`"
output: bookdown::gitbook
site: bookdown::bookdown_site
---

# Study material

## Lecture slides

The lecture slides will be added here.


## R programming: additional resources

 * R programming basics: [Base R](https://www.rstudio.com/wp-content/uploads/2016/10/r-cheat-sheet-3.pdf)
 * R visualization: [ggplot2](https://www.rstudio.com/wp-content/uploads/2016/11/ggplot2-cheatsheet-2.1.pdf) and [R graphics cookbook](http://www.cookbook-r.com/Graphs/)
 * Reproducible document generation with [R Markdown](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)  
 * [RStudio IDE](https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf)  
 * Microbiome bioinformatics in R: [List of R tools for microbiome analysis](https://microsud.github.io/Tools-Microbiome-Analysis/). See in particular [phyloseq](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0061217) and [microbiome tutorial](http://microbiome.github.io/tutorials/).
 * [Data Analysis and Visualization in R for Ecologists](https://datacarpentry.org/R-ecology-lesson/) by Data Carpentry


## Literature

- [Modern Statistics for Modern Biology. Holmes & Huber (2018)](http://web.stanford.edu/class/bios221/book/)

- [Signatures of ecological processes in microbial community time series. Faust K et al. Microbiome, 6(120) 2018]

- [Multi-stability and the origin of microbial community types. Faust et al. ISME Journal, 11:2159–2166, 2017]

- [Linking statistical and ecological theory: Hubbell’s unified neutral theory of biodiversity as a hierarchical Dirichlet process. Harris et al. Proceedings of the IEEE, 105(3):516–529, 2017]

- [Metagenomics meets time series analysis: unraveling microbial community dynamics. Faust K. Current Opinion in Microbiology, 25:56–66, 2015]

- [Microbial communities as dynamical systems. Gonze D et al. Current Opinion in Microbiology, 44:41–49, 2018]

- [Microbiome Data Science. Shetty & Lahti, 2019](https://openresearchlabs.github.io/publications/papers/2018-Shetty-Lahti-MDS.pdf)










